version: '3.7'
services:
  database:
    image: postgres
    restart: always
    networks:
      - backend
    env_file:
      - ./config/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 45s
      retries: 10
    volumes:
      - data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8090:8090"
    env_file:
      - ./config/.env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend

volumes:
  data:

networks:
  backend:
    driver: bridge